^README.md,package.json,scripts/launchd-generator,setup.cfg

diff --git a/scripts/launchd-generator b/scripts/launchd-generator
--- a/scripts/launchd-generator
+++ b/scripts/launchd-generator
@@ -15,109 +15,113 @@ EOF
 [[ $# == 0 ]] && usage
 
 PlistBuddy() { /usr/libexec/PlistBuddy "$@"; }
+get_type() {
+    [[ "$1" -gt -1 ]] 2> /dev/null && echo "integer" && return
+    [[ "$1" == "false" ]] || [[ "$1" == "true" ]] && echo "integer" && return
+    echo "string"
+}
+get_value() {
+    key="$1"
+    type="$2"
+    path="$3"
+    value="$(grep -i "$key: " "$path")"
+    [[ -z "$value" ]] && value="$(grep -i "$key@$type: " "$path")"
+    value="$(echo "$value" | awk -F ':' '{print $2}' | sed "s/^[ \t]*//")"
+    [[ "$value" == "Array {"* ]] && old="$(echo $value | tail -n +2 | sed '$d' |sed "s/^[ \t]*//")"
+    echo "${value//\~/$HOME}"
+}
+
+LAUNCHD_KEYS="Debug@bool
+Disabled@bool
+EnableGlobbing@bool
+GroupName@string
+KeepAlive@bool
+Label@string
+LaunchOnlyOnce@bool
+LowPriorityIO@bool
+QueueDirectories@array
+ProcessType@string
+ProgramArguments@array
+RunAtLoad@bool
+StandardInPath@string
+StandardErrorPath@string
+StandardOutPath@string
+StartInterval@integer
+StartOnMount@bool
+ThrottleInterval@integer
+WatchPaths@array
+UserName@string"
 
 while [[ $# != 0 ]]; do
+
     ! [ -e "$1" ] && echo "ERROR ($1): NOT EXISTS" && exit 1
     ! [ -f "$1" ] && echo "ERROR ($1): NOT A FILE" && exit 1
-    cat "$1" | head -1 | grep -q ^#! || { echo "ERROR ($1): SHEBANG #! REQUIRED" && exit 1; }
+    ! [ -s "$1" ] && echo "ERROR ($1): EMPTY FILE" && exit 1
+    cat "$1" | head -1 | grep -q ^#! || { echo "ERROR ($1): NOT A SCRIPT, shebang  #! required" && exit 1; }
+
+    unset Label ProgramArguments WorkingDirectory
     Program="$(cd "${1%/*}"; pwd -P)/${1##*/}"
-    ! [ -x "$Program" ] && { chmod +x "$Program" || exit; }
     PLIST="$Program".plist
 
-    # Label
-    Label="$(grep -i "Label: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ')"
     [[ -z "$Label" ]] && { relpath="${1/$PWD\//}"; Label="${relpath//\//_}"; }
     Label="$(echo "$Label" | sed 's/^.//' | sed 's/^_//')"
 
-    # StartInterval (int)
-    StartInterval="$(grep -i "StartInterval: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ')"
+    ProgramArguments="$Program
+$PLIST"
 
-    # KeepAlive (boolean, true/false)
-    KeepAlive="$(grep -i "KeepAlive: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ' | tr '[A-Z]' '[a-z]')"
-
-    # RunAtLoad (boolean, true/false)
-    RunAtLoad="$(grep -i "RunAtLoad: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ' | tr '[A-Z]' '[a-z]')"
-
-    # StandardErrorPath (string)
-    StandardErrorPath="$(grep -i "StandardErrorPath: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ')"
-    StandardErrorPath="${StandardErrorPath//\~/$HOME}"
-
-    # StandardOutPath (string)
-    StandardOutPath="$(grep -i "StandardOutPath: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ')"
-    StandardOutPath="${StandardOutPath//\~/$HOME}"
-
-    WatchPaths="$(grep -i "WatchPaths: " "$1" | awk -F ':' '{print $2}' | awk '{print $1}' | sed "s/^[ \t]*//")"
-    WatchPaths="${WatchPaths//\~/$HOME}"
-
-    # WorkingDirectory (string)
-    WorkingDirectory="$(grep -i "WorkingDirectory: " "$1" | head -1 | awk -F ':' '{print $2}' | awk '{print $1}' | tr -d ' ')"
-    WorkingDirectory="${WorkingDirectory//\~/$HOME}"
-    [[ -z "$WorkingDirectory" ]] && WorkingDirectory="${Program%/*}"
-
-    [[ -z "$KeepAlive" ]] && [[ -z "$RunAtLoad" ]] && [[ -z "$StartInterval" ]] && [[ -z "$WatchPaths" ]] && echo "SKIP ($1): KeepAlive/RunAtLoad/StartInterval/WatchPaths NOT FOUND" && shift && continue
+    WorkingDirectory="${Program%/*}"
 
     (
-        set -- /usr/libexec/PlistBuddy
-        # Label
-        old="$(PlistBuddy -c "Print Label" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && set "$@" -c "Add Label string '$Label'"
-        [[ -n "$old" ]] && set "$@" -c "Set Label '$Label'"
+        set --
+        keys_found=
 
-        # ProgramArguments
-        old="$(PlistBuddy -c "Print ProgramArguments" "$PLIST" 2> /dev/null)" || old=
-        [[ -n "$old" ]] && set "$@" -c "Delete :ProgramArguments"
-        set "$@" -c "Add :ProgramArguments array" \
-             -c "Add :ProgramArguments:0 string $Program"  \
-             -c "Add :ProgramArguments:1 string '$PLIST'"
+keys_matches="$(grep ": " "$Program")"
+[[ -n "$keys_matches" ]] && while IFS= read l; do
+    KEY_NAME="$(echo $l | awk -F':' '{print $1}' | awk '{print $(NF-0)}')"
+    KEY_VALUE="$(echo $l | awk -F':' '{print $2}' |sed "s/^[ \t]*//")"
+    KEY_TYPE="$(get_type "$KEY_VALUE")"
+    [[ "$KEY_NAME" == *@* ]] && {
+        KEY_TYPE="$(echo $KEY_NAME | awk -F'@' '{print $2}')"
+        [[ "$KEY_TYPE" == "bool" ]] || [[ "$KEY_TYPE" == "string" ]] || [[ "$KEY_TYPE" == "array" ]] || { echo "ERROR ($1): unsupported type - $KEY_TYPE" && exit 1; }
+        KEY_NAME="$(echo $KEY_NAME | awk -F'@' '{print $1}')"
+    }
+    [[ "${KEY_NAME:0:1}" == [A-Z] ]] && {
+        echo "$LAUNCHD_KEYS" | grep -q "$KEY_NAME@" || LAUNCHD_KEYS="$LAUNCHD_KEYS
+$KEY_NAME@$KEY_TYPE"
+    }
+done <<< "$keys_matches"
+        LAUNCHD_KEYS="$(echo "$LAUNCHD_KEYS" | sort -u)"
 
-        # KeepAlive
-        old="$(PlistBuddy -c "Print KeepAlive" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ "$KeepAlive" == "true" ]] && set "$@" -c "Add KeepAlive bool true"
-        [[ -n "$old" ]] && [[ "$KeepAlive" == "true" ]] && set "$@" -c "Set KeepAlive true"
-        [[ -n "$old" ]] && [[ "$KeepAlive" != "true" ]] && set "$@" -c "Delete KeepAlive"
+        while IFS= read KEY; do
+            KEY_NAME="$(echo "$KEY" | awk -F '@' '{print $1}')"
+            KEY_TYPE="$(echo "$KEY" | awk -F '@' '{print $2}')"
 
-        # RunAtLoad
-        old="$(PlistBuddy -c "Print RunAtLoad" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ "$RunAtLoad" == "true" ]] && set "$@" -c "Add RunAtLoad bool true"
-        [[ -n "$old" ]] && [[ "$RunAtLoad" == "true" ]] && set "$@" -c "Set RunAtLoad true"
-        [[ -n "$old" ]] && [[ "$RunAtLoad" != "true" ]] && set "$@" -c "Delete RunAtLoad"
+            new="$(get_value "$KEY_NAME" "$KEY_TYPE" "$Program")"
+            [[ -z "$new" ]] && new="${!KEY_NAME}" || keys_found=true
+            old="$(PlistBuddy -c "Print $KEY_NAME" "$PLIST" 2> /dev/null)" || old=
 
-        # StartInterval
-        old="$(/usr/libexec/PlistBuddy -c "Print StartInterval" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ -n "$StartInterval" ]] && set "$@" -c "Add StartInterval integer $StartInterval"
-        [[ -n "$old" ]] && [[ -n "$StartInterval" ]] && set "$@" -c "Set StartInterval $StartInterval"
-        [[ -n "$old" ]] && [[ -z "$StartInterval" ]] && set "$@" -c "Delete StartInterval"
-
-        # StandardErrorPath
-        old="$(PlistBuddy -c "Print StandardErrorPath" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ -n "$StandardErrorPath" ]] && set "$@" -c "Add StandardErrorPath string '$StandardErrorPath'"
-        [[ -n "$old" ]] && [[ -n "$StandardErrorPath" ]] && set "$@" -c "Set StandardErrorPath '$StandardErrorPath'"
-        [[ -n "$old" ]] && [[ -z "$StandardErrorPath" ]] && set "$@" -c "Delete StandardErrorPath"
-
-        # StandardOutPath
-        old="$(PlistBuddy -c "Print StandardOutPath" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ -n "$StandardOutPath" ]] && set "$@" -c "Add StandardOutPath string '$StandardOutPath'"
-        [[ -n "$old" ]] && [[ -n "$StandardOutPath" ]] && set "$@" -c "Set StandardOutPath '$StandardOutPath'"
-        [[ -n "$old" ]] && [[ -z "$StandardOutPath" ]] && set "$@" -c "Delete StandardOutPath"
-
-        # WorkingDirectory
-        old="$(PlistBuddy -c "Print WorkingDirectory" "$PLIST" 2> /dev/null)" || old=
-        [[ -z "$old" ]] && [[ -n "$WorkingDirectory" ]] && set "$@" -c "Add WorkingDirectory string '$WorkingDirectory'"
-        [[ -n "$old" ]] && [[ -n "$WorkingDirectory" ]] && set "$@" -c "Set WorkingDirectory '$WorkingDirectory'"
-        [[ -n "$old" ]] && [[ -z "$WorkingDirectory" ]] && set "$@" -c "Delete WorkingDirectory"
-
-        # WatchPaths
-        old="$(PlistBuddy -c "Print WatchPaths" "$PLIST" 2> /dev/null)" || old=
-        [[ -n "$old" ]] && set "$@" -c "Delete :WatchPaths"
-        [[ -n "$WatchPaths" ]] && {
-            set -- "$@" -c "Add :WatchPaths array"
-            i=0
-            while IFS= read path; do
-                set -- "$@" -c "Add :WatchPaths:$i string '$path'"
-                ((i++))
-            done <<< "$WatchPaths"
-        }
-        set -- "$@" "$PLIST"
+            [[ -n "$old" ]] && {
+                [[ -z "$new" ]] && set -- "$@" -c "Delete $KEY_NAME" && continue
+                [[ "$KEY_TYPE" == "array" ]] && [[ "$old" != "$new" ]] &&  {
+                    old=; set -- "$@" -c "Delete $KEY_NAME"
+                }
+                [[ "$KEY_TYPE" == "bool" ]] && [[ "$new" != "true" ]] && set -- "$@" -c "Delete $KEY_NAME"
+            }
+            [[ -z "$old" ]] && [[ -n "$new" ]] && {
+                [[ "$KEY_TYPE" != "array" ]] && set -- "$@" -c "Add $KEY_NAME $KEY_TYPE $new"
+                [[ "$KEY_TYPE" == "array" ]] && {
+                    set -- "$@" -c "Add $KEY_NAME $KEY_TYPE"
+                    i=0
+                    while IFS= read value; do
+                        set -- "$@" -c "Add :$KEY_NAME:$i string '$value'"
+                        ((i++))
+                    done <<< "$new"
+                }
+            }
+        done <<< "$LAUNCHD_KEYS"
+        [[ -z "$keys_found" ]] && echo "SKIP ($Program): launchd.plist keys not found" && exit
+        set -- /usr/libexec/PlistBuddy "$@" "$PLIST"
+        ! [ -x "$Program" ] && { chmod +x "$Program" || exit; }
         "$@" 1> /dev/null
     ) || exit
     shift
